CREATE TABLE users (id INT PRIMARY KEY AUTO_INCREMENT,name VARCHAR(255),email VARCHAR(255),password VARCHAR(255),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE files (id INT PRIMARY KEY AUTO_INCREMENT,name VARCHAR(255),mimetype VARCHAR(255),type VARCHAR(255),size INT,path VARCHAR(255),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
